#spring.application.name=foodapi
## Database connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/foodapi
#spring.datasource.username=postgres
#spring.datasource.password=root

# Driver
#spring.datasource.driver-class-name=org.postgresql.Driver

## JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#
## Show SQL (optional)
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#file.upload-dir=D:/uploads/food-images






spring.application.name=foodapi

spring.datasource.url=jdbc:postgresql://ep-restless-moon-atobvmfo.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_6OTYMSdtn7mw

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

file.upload-dir=D:/uploads/food-images